### ISSUE TITLE
Analysing official images is not allowed

### ISSUE THREAD

**Issue by deejanu** [wemanity-belgium/hyperclair#85]
Trying to understand how to make hyperclair to work. I tried to analyse 7 different images but I get the same error on all of them:

$ hyperclair analyse 1234567890ab
client quit unexpectedly
FATA[0000] pulling image "1234567890ab": analysing official images is not allowed

How do I analyse the images which I pull from Docker hub to make sure there are no issues?

**Comment by snemetz** [comment]
I have the same issue. Doesn't matter if the image came from Docker Hub or one created from a Dockerfile.

Not sure if this error is from hyperclair or clair. Will load another cli to figure out.

Not sure why this error even exists. Being an "official" image has nothing to do with being trusted. Security is about validating everything that is used.

**Comment by snemetz** [comment]
Just found one more thing related to this.
When the image is specified by id is gets the error "analysing official images is not allowed"
But if the image is specified by name or name and tag, it says "0 layers found" instead.

**Comment by snemetz** [comment]
Mine is working now. 
Needed to run like this:
${install_dir}/hyperclair push ${dockerImageName} --local
${install_dir}/hyperclair analyse ${dockerImageName} --local
${install_dir}/hyperclair report ${dockerImageName} --local

Debug log still shows most of the same errors. But it appears to be working now.

**Comment by deejanu** [comment]
We are running Clair v1.2.3 in a docker container, and installed hyperclair v0.5.2 on the same host where the docker container resides. We tried to run:
${install_dir}/hyperclair push ${dockerImageName} --local 
but received the same error:
FATA[0000] parsing local image "test": analysing official images is not allowed. We attempted to use the name as well as the ImageID however recieved the same error. 

Any Thoughts?

**Comment by snemetz** [comment]
I'd install analyze-local-images and see if that works. It provided me better error messages to get clair working. I was able to verify that clair was working correctly with it. Then I worked on hyperclair, knowing that any issue was in hyperclair and not clair.

The "official images" error message seems like it might be a default message for unknown failure.

**Comment by jgsqware** [comment]
hello
I got some integration problem whith layers coming from official images. 
however i'm integrating it directly into Clair threw the tool Clairctl. 
In this version this problem is fixed. 
PR should be merged soon 
https://github.com/coreos/clair/pull/164
i'll keep you in touch

**Comment by deejanu** [comment]
@snemetz We have Clair working correctly using Analyze-Local-Images and used the same image with HyperClair and received the message. 

@jgsqware What is ClairCTL? Is this like an experimental build of HyperClair?

Thanks for your help!

**Comment by snemetz** [comment]
Not sure how much more I can add. Once I got Analyze-Local-Images working, the only issue I had with hyperclair was in how I was referencing the images. It would not handle ids. I currently use repository/image name and tag. Since then it has been working fine. I'm also doing everything with local, not using any remote registry. Making this part of my CI image build workflow.

I looked at ClairCTL and it appears to an effort to integrate hyperclair into clair as the standard cli. Didn't notice any functional differences.

**Comment by jgsqware** [comment]
For the 'official image not supported' exception, the error is coming from
the way I retrieve layers from Hub.

In Clairctl I use the official docker library that manage official images.
So the issue should be fixed.

As you can see in the comment of the PR I need some times to make the build
pass and it will be merged.

At that time,  you will be able to use clairctl instead of hyperclair

Le lun. 8 août 2016 16:29, Steven Nemetz <notifications@github.com> a
écrit :

**Comment by deejanu** [comment]
Thanks for the response, can you point me to where I can find Clairctl?

**Comment by jgsqware** [comment]
Hello, clairctl is developed there now: github.com/jgsqware/clairctl.

It should fixed your problem
